--------------------------------------------------------
--  File created - 星期六-一月-18-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ACCOUNT" 
   (	"ID" VARCHAR2(32), 
	"LOGIN_NAME" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(100), 
	"PHONE" VARCHAR2(30), 
	"CREATE_TIME" DATE, 
	"STATUS" VARCHAR2(50)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."ID" IS '用户ID';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."LOGIN_NAME" IS '登录名';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."PASSWORD" IS '密码';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."NAME" IS '用户名';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."EMAIL" IS '邮箱';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."PHONE" IS '电话';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."CREATE_TIME" IS '更新时间';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT"."STATUS" IS '状态';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ACCOUNT_AUTH
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ACCOUNT_AUTH" 
   (	"ID" VARCHAR2(32), 
	"ACCOUNT_ID" VARCHAR2(32), 
	"ROLE" VARCHAR2(10)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT_AUTH"."ID" IS '授权id';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT_AUTH"."ACCOUNT_ID" IS '用户ID';
   COMMENT ON COLUMN "GE_MONITOR_ACCOUNT_AUTH"."ROLE" IS '角色';
   COMMENT ON TABLE "GE_MONITOR_ACCOUNT_AUTH"  IS '用户授权表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ALARM
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ALARM" 
   (	"ID" VARCHAR2(32), 
	"SEVERITY" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(3000), 
	"ALARM_SOURCE" VARCHAR2(20), 
	"MONITOR_ID" VARCHAR2(32), 
	"MONITOR_TYPE" VARCHAR2(50), 
	"ATTRIBUTE_ID" VARCHAR2(32), 
	"CREATE_TIME" DATE, 
	"OWNER_NAME" VARCHAR2(100), 
	"SUB_RESOURCE_TYPE" VARCHAR2(32), 
	"SUB_RESOURCE_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ALARM"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."SEVERITY" IS '严重级别(severity)';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."MESSAGE" IS '警报信息(message)';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."ALARM_SOURCE" IS '警报来源(日志,异常)';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."MONITOR_ID" IS '监视器ID';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."MONITOR_TYPE" IS '监视器类型';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."ATTRIBUTE_ID" IS '属性ID';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."CREATE_TIME" IS '创建时间(createtime)';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."OWNER_NAME" IS '所有者(ownername)';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."SUB_RESOURCE_TYPE" IS '子资源类型';
   COMMENT ON COLUMN "GE_MONITOR_ALARM"."SUB_RESOURCE_ID" IS '子资源ID';
   COMMENT ON TABLE "GE_MONITOR_ALARM"  IS '应用系统预警信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_APPLICATION
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_APPLICATION" 
   (	"ID" VARCHAR2(32), 
	"APPLICATION_NAME" VARCHAR2(100), 
	"CN_NAME" VARCHAR2(300), 
	"APPLICATION_IP" VARCHAR2(100), 
	"APPLICATION_PORT" VARCHAR2(5), 
	"CREATE_TIME" DATE, 
	"CREATOR_ID" VARCHAR2(32), 
	"MODIFY_TIME" DATE, 
	"MODIFIER_ID" VARCHAR2(32), 
	"STATUS" VARCHAR2(1) DEFAULT '1', 
	"INTERVAL" NUMBER
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."APPLICATION_NAME" IS '应用系统英文名称';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."CN_NAME" IS '应用系统中文名称';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."CREATOR_ID" IS '创建人ID';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."MODIFIER_ID" IS '修改人ID';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."STATUS" IS '有效状态:1有效,0删除';
   COMMENT ON COLUMN "GE_MONITOR_APPLICATION"."INTERVAL" IS '轮询间隔';
   COMMENT ON TABLE "GE_MONITOR_APPLICATION"  IS '存储需要监控的应用系统信息';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ATTRIBUTE
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ATTRIBUTE" 
   (	"ID" VARCHAR2(32), 
	"RESOURCE_TYPE" VARCHAR2(32), 
	"ATTRIBUTE" VARCHAR2(255), 
	"UNITS" VARCHAR2(10), 
	"ATTRIBUTE_CN" VARCHAR2(255)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE"."RESOURCE_TYPE" IS '资源类型';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE"."ATTRIBUTE" IS '属性';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE"."UNITS" IS '单位';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE"."ATTRIBUTE_CN" IS '属性中文名称';
   COMMENT ON TABLE "GE_MONITOR_ATTRIBUTE"  IS '属性信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ATTRIBUTE_ACTION
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ATTRIBUTE_ACTION" 
   (	"ID" VARCHAR2(32), 
	"RESOURCE_ID" VARCHAR2(32), 
	"ATTRIBUTE_ID" VARCHAR2(32), 
	"ACTION_ID" VARCHAR2(32), 
	"ACTION_TYPE" VARCHAR2(20), 
	"SEVERITY" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."RESOURCE_ID" IS '资源ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."ATTRIBUTE_ID" IS '属性ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."ACTION_ID" IS '动作ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."ACTION_TYPE" IS '动作类型';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_ACTION"."SEVERITY" IS '严重程度';
   COMMENT ON TABLE "GE_MONITOR_ATTRIBUTE_ACTION"  IS '属性动作信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ATTRIBUTE_THRESHOLD
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" 
   (	"ID" VARCHAR2(32), 
	"RESOURCE_ID" VARCHAR2(32), 
	"ATTRIBUTE_ID" VARCHAR2(32), 
	"THRESHOLD_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_THRESHOLD"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_THRESHOLD"."RESOURCE_ID" IS '资源ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_THRESHOLD"."ATTRIBUTE_ID" IS '属性ID';
   COMMENT ON COLUMN "GE_MONITOR_ATTRIBUTE_THRESHOLD"."THRESHOLD_ID" IS '阈值ID';
   COMMENT ON TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD"  IS '属性阈值信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_BIZ_SCENARIO
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_BIZ_SCENARIO" 
   (	"ID" VARCHAR2(32), 
	"NAME" VARCHAR2(300), 
	"BIZ_SCENARIO_GRADE" VARCHAR2(15), 
	"APPLICATION_ID" VARCHAR2(32), 
	"CREATE_TIME" DATE, 
	"CREATOR_ID" VARCHAR2(32), 
	"MODIFY_TIME" DATE, 
	"MODIFIER_ID" VARCHAR2(32), 
	"STATUS" VARCHAR2(1) DEFAULT '1'
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."NAME" IS '业务场景名称';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."BIZ_SCENARIO_GRADE" IS '业务场景级别';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."APPLICATION_ID" IS '所属应用系统ID';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."CREATOR_ID" IS '创建人ID';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."MODIFIER_ID" IS '修改人ID';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO"."STATUS" IS '有效状态:1有效,0删除';
   COMMENT ON TABLE "GE_MONITOR_BIZ_SCENARIO"  IS '存储指定应用系统的业务场景信息';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_BIZ_SCENARIO_URL
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_BIZ_SCENARIO_URL" 
   (	"BIZ_SCENARIO_ID" VARCHAR2(32), 
	"URL_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO_URL"."BIZ_SCENARIO_ID" IS '业务场景ID';
   COMMENT ON COLUMN "GE_MONITOR_BIZ_SCENARIO_URL"."URL_ID" IS 'URLID';
   COMMENT ON TABLE "GE_MONITOR_BIZ_SCENARIO_URL"  IS '应用系统业务场景URL信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_EMAIL_ACTION
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_EMAIL_ACTION" 
   (	"ID" VARCHAR2(32), 
	"FROM_ADDRESS" VARCHAR2(250), 
	"TO_ADDRESS" VARCHAR2(250), 
	"SUBJECT" VARCHAR2(100), 
	"CONTENT" VARCHAR2(3000), 
	"SMTP_SERVER" VARCHAR2(100), 
	"SMTP_PORT" VARCHAR2(5), 
	"MAIL_FORMAT" VARCHAR2(1), 
	"APPEND_MESSAGE" VARCHAR2(100), 
	"NAME" VARCHAR2(100)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."FROM_ADDRESS" IS '发件地址(fromaddress)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."TO_ADDRESS" IS '收件地址(toaddress)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."SUBJECT" IS '主题(subject)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."CONTENT" IS '内容(message)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."SMTP_SERVER" IS '邮件服务器(smtpserver)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."SMTP_PORT" IS '邮件服务器端口(smtpport)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."MAIL_FORMAT" IS '邮件格式(mailformat)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."APPEND_MESSAGE" IS '附加信息(appendmessage)';
   COMMENT ON COLUMN "GE_MONITOR_EMAIL_ACTION"."NAME" IS '动作名称(name)';
   COMMENT ON TABLE "GE_MONITOR_EMAIL_ACTION"  IS '应用系统邮件动作信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_EUM_URL
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_EUM_URL" 
   (	"ID" VARCHAR2(32), 
	"URL" VARCHAR2(300), 
	"APPLICATION_ID" VARCHAR2(32), 
	"RECORD_TIME" DATE, 
	"URL_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_EUM_URL"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL"."URL" IS 'URL地址';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL"."APPLICATION_ID" IS '所属应用系统ID';
   COMMENT ON TABLE "GE_MONITOR_EUM_URL"  IS '业务仿真URL信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_EUM_URL_AVA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_EUM_URL_AVA" 
   (	"ID" VARCHAR2(32), 
	"EUM_URL_ID" VARCHAR2(32), 
	"STATE" VARCHAR2(1), 
	"RECORD_TIME" DATE, 
	"INTERVAL" NUMBER
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA"."EUM_URL_ID" IS '业务仿真ID';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA"."STATE" IS '状态 1---可用 0---不可用';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA"."RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA"."INTERVAL" IS '轮询间隔';
   COMMENT ON TABLE "GE_MONITOR_EUM_URL_AVA"  IS '应用系统可用性临时表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_EUM_URL_AVA_STA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_EUM_URL_AVA_STA" 
   (	"ID" VARCHAR2(32), 
	"EUM_URL_ID" VARCHAR2(32), 
	"NORMAL_RUNTIME" NUMBER, 
	"TOTAL_FAILURE_TIME" NUMBER, 
	"FAILURE_COUNT" NUMBER, 
	"AVG_FAILURE_TIME" NUMBER, 
	"RECORD_TIME" DATE
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."EUM_URL_ID" IS '业务仿真URLID';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."NORMAL_RUNTIME" IS '正常运行时间';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."TOTAL_FAILURE_TIME" IS '总失败时间';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."FAILURE_COUNT" IS '停止次数';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."AVG_FAILURE_TIME" IS '平均故障间隔时间';
   COMMENT ON COLUMN "GE_MONITOR_EUM_URL_AVA_STA"."RECORD_TIME" IS '记录时间';
   COMMENT ON TABLE "GE_MONITOR_EUM_URL_AVA_STA"  IS '业务仿真URL可用性统计表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_EXCEPTION_INFO
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_EXCEPTION_INFO" 
   (	"ID" VARCHAR2(32), 
	"APPLICATION_ID" VARCHAR2(32), 
	"EXCEPTION_DESCRIPTION" VARCHAR2(500), 
	"EXCEPTION_STACK_TRACE" CLOB, 
	"RECORD_TIME" DATE, 
	"URL_TRACE_LOG_ID" VARCHAR2(32), 
	"ALARM_ID" VARCHAR2(32), 
	"URL" VARCHAR2(300), 
	"REQUEST_PARAMS" CLOB
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."APPLICATION_ID" IS '所属应用系统';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."EXCEPTION_DESCRIPTION" IS '异常描述';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."EXCEPTION_STACK_TRACE" IS '异常堆栈';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."RECORD_TIME" IS '异常时间';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."URL_TRACE_LOG_ID" IS 'URL追踪日志ID';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."ALARM_ID" IS '告警消息ID';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."URL" IS 'URL地址';
   COMMENT ON COLUMN "GE_MONITOR_EXCEPTION_INFO"."REQUEST_PARAMS" IS 'URL请求参数';
   COMMENT ON TABLE "GE_MONITOR_EXCEPTION_INFO"  IS '记录所有的异常信息';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_GROUP
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_GROUP" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_GROUP_PERMISSION
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_GROUP_PERMISSION" 
   (	"GROUP_ID" NUMBER(19,0), 
	"PERMISSION" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_METHOD
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_METHOD" 
   (	"ID" VARCHAR2(32), 
	"DESCRIPTION" VARCHAR2(300), 
	"CLASS_NAME" VARCHAR2(500), 
	"METHOD_NAME" VARCHAR2(100), 
	"THRESHOLD" NUMBER(6,0), 
	"CREATE_TIME" DATE, 
	"CREATOR_ID" VARCHAR2(32), 
	"MODIFY_TIME" DATE, 
	"MODIFIER_ID" VARCHAR2(32), 
	"STATUS" VARCHAR2(1) DEFAULT '1'
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_METHOD"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."DESCRIPTION" IS '方法描述';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."CLASS_NAME" IS '方法所属类名';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."METHOD_NAME" IS '方法名称';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."THRESHOLD" IS '方法阈值,单位ms';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."CREATOR_ID" IS '创建人ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."MODIFIER_ID" IS '修改人ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD"."STATUS" IS '有效状态:1有效,0删除';
   COMMENT ON TABLE "GE_MONITOR_METHOD"  IS '应用系统方法信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_METHOD_RESPONSETIME
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_METHOD_RESPONSETIME" 
   (	"ID" VARCHAR2(32), 
	"METHOD_NAME" VARCHAR2(300), 
	"URL_ID" VARCHAR2(32), 
	"MIN_RESPONSE_TIME" NUMBER, 
	"MAX_RESPONSE_TIME" NUMBER, 
	"TOTAL_RESPONSE_TIME" NUMBER, 
	"TOTAL_COUNT" NUMBER, 
	"APPLICATION_ID" VARCHAR2(32), 
	"RECORD_TIME" DATE, 
	"METHOD_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."METHOD_NAME" IS '方法名';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."URL_ID" IS 'URL信息ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."MIN_RESPONSE_TIME" IS '最小响应时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."MAX_RESPONSE_TIME" IS '最大响应时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."TOTAL_RESPONSE_TIME" IS '总响应时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."TOTAL_COUNT" IS '总次数';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."APPLICATION_ID" IS '所属应用系统';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_RESPONSETIME"."METHOD_ID" IS '方法信息ID';
   COMMENT ON TABLE "GE_MONITOR_METHOD_RESPONSETIME"  IS '方法响应时间';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_METHOD_TL_TEMP
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_METHOD_TL_TEMP" 
   (	"ID" VARCHAR2(32), 
	"URL_TRACE_LOG_ID" VARCHAR2(32), 
	"METHOD_NAME" VARCHAR2(100), 
	"CLASS_NAME" VARCHAR2(200), 
	"IN_PARAM" CLOB, 
	"OUT_PARAM" CLOB, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"CONSUME_TIME" NUMBER, 
	"RECORD_TIME" DATE, 
	"METHOD_ID" VARCHAR2(32)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_METHOD_TRACE_LOG
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_METHOD_TRACE_LOG" 
   (	"ID" VARCHAR2(32), 
	"URL_TRACE_LOG_ID" VARCHAR2(32), 
	"METHOD_NAME" VARCHAR2(100), 
	"CLASS_NAME" VARCHAR2(200), 
	"IN_PARAM" CLOB, 
	"OUT_PARAM" CLOB, 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"CONSUME_TIME" NUMBER, 
	"RECORD_TIME" DATE, 
	"METHOD_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."URL_TRACE_LOG_ID" IS 'URL追踪日志ID';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."METHOD_NAME" IS '方法名';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."CLASS_NAME" IS '方法所属类名';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."IN_PARAM" IS '方法输入参数';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."OUT_PARAM" IS '方法输入参数';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."BEGIN_TIME" IS '方法开始时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."END_TIME" IS '方法结束时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."CONSUME_TIME" IS 'URL执行时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."RECORD_TIME" IS '日志记录时间';
   COMMENT ON COLUMN "GE_MONITOR_METHOD_TRACE_LOG"."METHOD_ID" IS '方法信息ID';
   COMMENT ON TABLE "GE_MONITOR_METHOD_TRACE_LOG"  IS '方法追踪日志信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ORACLE_AVA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ORACLE_AVA" 
   (	"ID" VARCHAR2(32), 
	"DATABASE_ID" VARCHAR2(32), 
	"RECORD_TIME" DATE, 
	"STATE" VARCHAR2(1), 
	"INTERVAL" NUMBER
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA"."DATABASE_ID" IS '数据库ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA"."RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA"."STATE" IS '0.不可用,1.可用';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA"."INTERVAL" IS '轮询间隔时间';
   COMMENT ON TABLE "GE_MONITOR_ORACLE_AVA"  IS 'ORACLE可用性临时表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ORACLE_AVA_STA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ORACLE_AVA_STA" 
   (	"ID" VARCHAR2(32), 
	"DATABASE_ID" VARCHAR2(32), 
	"NORMAL_RUNTIME" NUMBER, 
	"TOTAL_POWEROFF_TIME" NUMBER, 
	"POWEROFF_COUNT" NUMBER, 
	"AVG_FAILURE_TIME" NUMBER, 
	"AVA_RECORD_TIME" DATE, 
	"AV_COUNT" NUMBER, 
	"UNAV_COUNT" NUMBER, 
	"UNKNOW_TIME" NUMBER, 
	"RECORD_TIME" DATE
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."DATABASE_ID" IS '数据库ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."NORMAL_RUNTIME" IS '正常运行时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."TOTAL_POWEROFF_TIME" IS '总停机时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."POWEROFF_COUNT" IS '停机次数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."AVG_FAILURE_TIME" IS '平均故障间隔时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."AVA_RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."AV_COUNT" IS '可用次数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."UNAV_COUNT" IS '不可用次数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."UNKNOW_TIME" IS '未知时间总数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_AVA_STA"."RECORD_TIME" IS '创建时间';
   COMMENT ON TABLE "GE_MONITOR_ORACLE_AVA_STA"  IS 'ORACLE可用性统计表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ORACLE_EVENT_STA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ORACLE_EVENT_STA" 
   (	"ID" VARCHAR2(32), 
	"DATABASE_ID" VARCHAR2(32), 
	"EVENT_TYPE" VARCHAR2(2), 
	"MIN" FLOAT(126), 
	"MAX" FLOAT(126), 
	"AVG" FLOAT(126), 
	"EVENT_RECORD_TIME" DATE, 
	"EVENT_COUNT" NUMBER(*,0), 
	"RECORD_TIME" DATE
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."DATABASE_ID" IS '数据库ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."EVENT_TYPE" IS '1:连接时间,2:活动连接数,3:缓冲区命中率,4.数据字典命中率,5.缓存库命中率';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."MIN" IS '活动连接数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."MAX" IS '活动连接数最大值';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."AVG" IS '平均值';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."EVENT_RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."EVENT_COUNT" IS '统计次数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_EVENT_STA"."RECORD_TIME" IS '创建时间';
   COMMENT ON TABLE "GE_MONITOR_ORACLE_EVENT_STA"  IS 'ORACLE事件统计表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ORACLE_INFO
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ORACLE_INFO" 
   (	"ID" VARCHAR2(32), 
	"NAME" VARCHAR2(80), 
	"ORACLE_VERSION" VARCHAR2(50), 
	"IP_ADDRESS" VARCHAR2(30), 
	"SUBNET_MASK" VARCHAR2(30), 
	"PORT" VARCHAR2(5), 
	"PULL_INTERVAL" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(50), 
	"INSTANCE_NAME" VARCHAR2(20), 
	"SYS_TIME" DATE, 
	"START_TIME" VARCHAR2(50)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."NAME" IS '名称';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."ORACLE_VERSION" IS '版本';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."IP_ADDRESS" IS 'IP地址';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."SUBNET_MASK" IS '子网掩码';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."PORT" IS '端口';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."PULL_INTERVAL" IS '轮询间隔';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."USERNAME" IS '用户名';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."PASSWORD" IS '密码';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."INSTANCE_NAME" IS '服务名';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."SYS_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_INFO"."START_TIME" IS '启动时间';
   COMMENT ON TABLE "GE_MONITOR_ORACLE_INFO"  IS 'Oracle数据库信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_ORACLE_LASTEVENT
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_ORACLE_LASTEVENT" 
   (	"ID" VARCHAR2(32), 
	"DATABASE_ID" VARCHAR2(32), 
	"ACTIVE_COUNT" NUMBER, 
	"CONNECT_TIME" NUMBER, 
	"BUFFER_HIT_RATE" NUMBER(*,6), 
	"DICK_HIT_RATE" NUMBER(*,6), 
	"BUFFER_LIB_HIT_RATE" NUMBER(*,6), 
	"RECORD_TIME" DATE
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."DATABASE_ID" IS '数据库ID';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."ACTIVE_COUNT" IS '活动连接数';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."CONNECT_TIME" IS '连接时间';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."BUFFER_HIT_RATE" IS '缓冲区命中率';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."DICK_HIT_RATE" IS '数据字典命中率';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."BUFFER_LIB_HIT_RATE" IS '缓存库命中率';
   COMMENT ON COLUMN "GE_MONITOR_ORACLE_LASTEVENT"."RECORD_TIME" IS '记录时间';
   COMMENT ON TABLE "GE_MONITOR_ORACLE_LASTEVENT"  IS 'ORACLE最近一小时事件记录';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS" 
   (	"OS_INFO_ID" VARCHAR2(32), 
	"NAME" VARCHAR2(16), 
	"TYPE" VARCHAR2(16), 
	"IP_ADDR" VARCHAR2(16), 
	"SUBNET_MASK" VARCHAR2(16), 
	"INTERCYCLE_TIME" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_AVAILABLE
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_AVAILABLE" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"NORMAL_RUN" NUMBER, 
	"CRASH_TIME" NUMBER, 
	"AVE_REPAIR_TIME" NUMBER, 
	"AVE_FAULT_TIME" NUMBER, 
	"TIME_SPAN" DATE, 
	"STOP_COUNT" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_AVAILABLETEMP
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_AVAILABLETEMP" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"SAMPLE_DATE" DATE, 
	"STATUS" VARCHAR2(2), 
	"INTERCYCLE_TIME" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_CPU
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_CPU" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"SAMPLE_DATE" DATE, 
	"UTILI_ZATION" VARCHAR2(10), 
	"RUN_QUEUE" VARCHAR2(10), 
	"BLOCK_PROCESS" VARCHAR2(10), 
	"USER_TIME" VARCHAR2(10), 
	"SYS_TIME" VARCHAR2(10), 
	"IO_WAIT" VARCHAR2(10), 
	"CPU_IDLE" VARCHAR2(10), 
	"INTER_RUPT" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_DISK
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_DISK" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"DISK_PATH" VARCHAR2(32), 
	"TOTAL" VARCHAR2(20), 
	"USED" VARCHAR2(20), 
	"FREE" VARCHAR2(20), 
	"USED_UTILI_ZATION" VARCHAR2(20), 
	"FREE_UTILI_ZATION" VARCHAR2(20), 
	"SAMPLE_DATE" DATE, 
	"MOUNT_POINT" VARCHAR2(20), 
	"TOTAL_UTILI_ZATION" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_RAM
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_RAM" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"SAMPLE_DATE" DATE, 
	"MEM_TOTAL" VARCHAR2(20), 
	"MEM_USED" VARCHAR2(20), 
	"MEM_UTILI_ZATION" VARCHAR2(8), 
	"SWAP_TOTAL" VARCHAR2(20), 
	"SWAP_USED" VARCHAR2(20), 
	"SWAP_UTILI_ZATION" VARCHAR2(8)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_RESPONDTIME
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_RESPONDTIME" 
   (	"ID" VARCHAR2(32), 
	"OS_INFO_ID" VARCHAR2(32), 
	"SAMPLE_DATE" DATE, 
	"RESPOND_TIME" VARCHAR2(32)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_SHELL
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_SHELL" 
   (	"ID" VARCHAR2(32), 
	"TYPE" VARCHAR2(2), 
	"TEMPLATE" CLOB
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_OS_STATI
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_OS_STATI" 
   (	"ID" VARCHAR2(32), 
	"OSID" VARCHAR2(32), 
	"TYPE" VARCHAR2(2), 
	"RECORD_TIME" DATE, 
	"MIN_VALUE" VARCHAR2(20), 
	"MAX_VALUE" VARCHAR2(20), 
	"AVERAGE_VALUE" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_REQUEST_PER_MINUTE
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_REQUEST_PER_MINUTE" 
   (	"ID" VARCHAR2(32), 
	"APPLICATION_ID" VARCHAR2(32), 
	"REQUEST_NUMBER" NUMBER, 
	"RECORD_TIME" DATE
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_REQUEST_PER_MINUTE"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_REQUEST_PER_MINUTE"."APPLICATION_ID" IS '所属应用系统ID';
   COMMENT ON COLUMN "GE_MONITOR_REQUEST_PER_MINUTE"."REQUEST_NUMBER" IS '请求数';
   COMMENT ON COLUMN "GE_MONITOR_REQUEST_PER_MINUTE"."RECORD_TIME" IS '记录时间';
   COMMENT ON TABLE "GE_MONITOR_REQUEST_PER_MINUTE"  IS '应用系统每分钟请求数';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_RESOURCES
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_RESOURCES" 
   (	"RESOURCE_ID" VARCHAR2(32), 
	"RESOURCE_NAME" VARCHAR2(300), 
	"RESOURCE_TYPE" VARCHAR2(100)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_RESOURCES"."RESOURCE_ID" IS '资源ID';
   COMMENT ON COLUMN "GE_MONITOR_RESOURCES"."RESOURCE_NAME" IS '资源名称';
   COMMENT ON COLUMN "GE_MONITOR_RESOURCES"."RESOURCE_TYPE" IS '资源类型';
   COMMENT ON TABLE "GE_MONITOR_RESOURCES"  IS '资源表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_SMS
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_SMS" 
   (	"ID" VARCHAR2(32), 
	"APPID" VARCHAR2(50), 
	"OWNER" VARCHAR2(100), 
	"PHONENO" VARCHAR2(25), 
	"CREATE_TIME" DATE, 
	"STATUS" VARCHAR2(1), 
	"REMARK" VARCHAR2(200)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_SMS"."ID" IS '序列';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."APPID" IS '应用ID';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."OWNER" IS '用户名';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."PHONENO" IS '短信号码';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."STATUS" IS '短信状态';
   COMMENT ON COLUMN "GE_MONITOR_SMS"."REMARK" IS '备注';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_THRESHOLD
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_THRESHOLD" 
   (	"ID" VARCHAR2(32), 
	"NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(250), 
	"CRITICAL_THRESHOLD_CONDITION" VARCHAR2(2), 
	"CRITICAL_THRESHOLD_VALUE" NUMBER, 
	"CRITICAL_THRESHOLD_MESSAGE" VARCHAR2(250), 
	"WARNING_THRESHOLD_CONDITION" VARCHAR2(2), 
	"WARNING_THRESHOLD_VALUE" NUMBER, 
	"WARNING_THRESHOLD_MESSAGE" VARCHAR2(250), 
	"INFO_THRESHOLD_CONDITION" VARCHAR2(2), 
	"INFO_THRESHOLD_VALUE" NUMBER, 
	"INFO_THRESHOLD_MESSAGE" VARCHAR2(250)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."NAME" IS '名称';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."DESCRIPTION" IS '描述';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."CRITICAL_THRESHOLD_CONDITION" IS '临界阈值条件';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."CRITICAL_THRESHOLD_VALUE" IS '临界阈值值';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."CRITICAL_THRESHOLD_MESSAGE" IS '临界阈值信息';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."WARNING_THRESHOLD_CONDITION" IS '警告阈值条件';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."WARNING_THRESHOLD_VALUE" IS '警告阈值值';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."WARNING_THRESHOLD_MESSAGE" IS '警告阈值信息';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."INFO_THRESHOLD_CONDITION" IS '正常阈值条件';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."INFO_THRESHOLD_VALUE" IS '正常阈值值';
   COMMENT ON COLUMN "GE_MONITOR_THRESHOLD"."INFO_THRESHOLD_MESSAGE" IS '正常阈值信息';
   COMMENT ON TABLE "GE_MONITOR_THRESHOLD"  IS '阈值信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL" 
   (	"ID" VARCHAR2(32), 
	"DESCRIPTION" VARCHAR2(300), 
	"URL" VARCHAR2(500), 
	"THRESHOLD" NUMBER(6,0), 
	"CREATE_TIME" DATE, 
	"CREATOR_ID" VARCHAR2(32), 
	"MODIFY_TIME" DATE, 
	"MODIFIER_ID" VARCHAR2(32), 
	"STATUS" VARCHAR2(1) DEFAULT '1'
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_URL"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_URL"."DESCRIPTION" IS 'URL描述';
   COMMENT ON COLUMN "GE_MONITOR_URL"."URL" IS 'URL地址';
   COMMENT ON COLUMN "GE_MONITOR_URL"."THRESHOLD" IS 'URL阈值，单位ms';
   COMMENT ON COLUMN "GE_MONITOR_URL"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "GE_MONITOR_URL"."CREATOR_ID" IS '创建人ID';
   COMMENT ON COLUMN "GE_MONITOR_URL"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "GE_MONITOR_URL"."MODIFIER_ID" IS '修改人ID';
   COMMENT ON COLUMN "GE_MONITOR_URL"."STATUS" IS '有效状态:1有效,0删除';
   COMMENT ON TABLE "GE_MONITOR_URL"  IS '应用系统URL信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL_METHOD
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL_METHOD" 
   (	"URL_ID" VARCHAR2(32), 
	"METHOD_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_URL_METHOD"."URL_ID" IS 'URLID';
   COMMENT ON COLUMN "GE_MONITOR_URL_METHOD"."METHOD_ID" IS '方法ID';
   COMMENT ON TABLE "GE_MONITOR_URL_METHOD"  IS '应用系统URL方法信息表';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL_RESPONSE_TIME
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL_RESPONSE_TIME" 
   (	"ID" VARCHAR2(32), 
	"URL" VARCHAR2(300), 
	"URL_ID" VARCHAR2(32), 
	"MIN_RESPONSE_TIME" NUMBER, 
	"MAX_RESPONSE_TIME" NUMBER, 
	"TOTAL_RESPONSE_TIME" NUMBER, 
	"RECORD_TIME" DATE, 
	"APPLICATION_ID" VARCHAR2(32), 
	"TOTAL_COUNT" NUMBER
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."URL" IS 'URL地址';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."URL_ID" IS 'URL信息ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."MIN_RESPONSE_TIME" IS '最小响应时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."MAX_RESPONSE_TIME" IS '最大响应时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."TOTAL_RESPONSE_TIME" IS '总响应时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."APPLICATION_ID" IS '所属应用系统';
   COMMENT ON COLUMN "GE_MONITOR_URL_RESPONSE_TIME"."TOTAL_COUNT" IS '总次数';
   COMMENT ON TABLE "GE_MONITOR_URL_RESPONSE_TIME"  IS 'URL响应时间';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL_TRACE_LOG
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL_TRACE_LOG" 
   (	"ID" VARCHAR2(32), 
	"URL" VARCHAR2(500), 
	"URL_ID" VARCHAR2(32), 
	"BIZ_SCENARIO_ID" VARCHAR2(32), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"CONSUME_TIME" NUMBER, 
	"SESSION_ID" VARCHAR2(100), 
	"USER_ID" VARCHAR2(32), 
	"USER_IP" VARCHAR2(100), 
	"TRACE_ID" VARCHAR2(32), 
	"REQUEST_PARAMS" CLOB, 
	"ALARM_ID" VARCHAR2(32), 
	"RECORD_TIME" DATE, 
	"USERNAME" VARCHAR2(200), 
	"APPLICATION_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."URL" IS 'URL地址';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."URL_ID" IS 'URL信息ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."BIZ_SCENARIO_ID" IS '所属业务场景ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."BEGIN_TIME" IS 'URL开始时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."END_TIME" IS 'URL结束时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."CONSUME_TIME" IS 'URL执行时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."SESSION_ID" IS '会话ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."USER_ID" IS '用户ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."USER_IP" IS '用户IP';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."TRACE_ID" IS '追踪ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."REQUEST_PARAMS" IS '请求参数信息';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."ALARM_ID" IS '告警信息ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."RECORD_TIME" IS '日志记录时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."USERNAME" IS '用户名';
   COMMENT ON COLUMN "GE_MONITOR_URL_TRACE_LOG"."APPLICATION_ID" IS '应用系统ID';
   COMMENT ON TABLE "GE_MONITOR_URL_TRACE_LOG"  IS '记录应用系统URL追踪日志信息';
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL_TRACE_LOG_TEMP
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL_TRACE_LOG_TEMP" 
   (	"ID" VARCHAR2(32), 
	"URL" VARCHAR2(500), 
	"URL_ID" VARCHAR2(32), 
	"BIZ_SCENARIO_ID" VARCHAR2(32), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"CONSUME_TIME" NUMBER, 
	"SESSION_ID" VARCHAR2(100), 
	"USER_ID" VARCHAR2(32), 
	"USER_IP" VARCHAR2(100), 
	"TRACE_ID" VARCHAR2(32), 
	"REQUEST_PARAMS" CLOB, 
	"ALARM_ID" VARCHAR2(32), 
	"RECORD_TIME" DATE, 
	"USERNAME" VARCHAR2(200), 
	"APPLICATION_ID" VARCHAR2(32)
   ) ;
--------------------------------------------------------
--  DDL for Table GE_MONITOR_URL_VISITS_STA
--------------------------------------------------------

  CREATE TABLE "GE_MONITOR_URL_VISITS_STA" 
   (	"ID" VARCHAR2(32), 
	"URL_ID" VARCHAR2(32), 
	"VISIT_NUMBER" NUMBER, 
	"RECORD_TIME" DATE, 
	"APPLICATION_ID" VARCHAR2(32)
   ) ;

   COMMENT ON COLUMN "GE_MONITOR_URL_VISITS_STA"."ID" IS '主键ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_VISITS_STA"."URL_ID" IS 'URL信息ID';
   COMMENT ON COLUMN "GE_MONITOR_URL_VISITS_STA"."VISIT_NUMBER" IS '访问量';
   COMMENT ON COLUMN "GE_MONITOR_URL_VISITS_STA"."RECORD_TIME" IS '记录时间';
   COMMENT ON COLUMN "GE_MONITOR_URL_VISITS_STA"."APPLICATION_ID" IS '所属应用系统ID';
   COMMENT ON TABLE "GE_MONITOR_URL_VISITS_STA"  IS '应用系统URL访问量统计';
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ACCOUNT" ADD CONSTRAINT "PK_GE_MONITOR_ACCOUNT" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ACCOUNT_AUTH
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ACCOUNT_AUTH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ACCOUNT_AUTH" ADD CONSTRAINT "PK_GE_MONITOR_ACCOUNT_AUTH" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ALARM
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ALARM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ALARM" ADD CONSTRAINT "PK_GE_MONITOR_ALARM" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_APPLICATION
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_APPLICATION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_APPLICATION" MODIFY ("CREATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_APPLICATION" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_APPLICATION" MODIFY ("APPLICATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_APPLICATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_APPLICATION" ADD CONSTRAINT "PK_GE_MONITOR_APPLICATION" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ATTRIBUTE
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ATTRIBUTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE" ADD CONSTRAINT "PK_GE_MONITOR_ATTRIBUTE" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ATTRIBUTE_ACTION
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" MODIFY ("SEVERITY" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_ACTION" ADD CONSTRAINT "PK_GE_MONITOR_ATTRIBUTE_ACTION" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ATTRIBUTE_THRESHOLD
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" MODIFY ("THRESHOLD_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ATTRIBUTE_THRESHOLD" ADD CONSTRAINT "PK_GE_MONITOR_ATTRIBUTE_THRESH" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_BIZ_SCENARIO
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("CREATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" ADD CONSTRAINT "PK_GE_MONITOR_BIZ_SCENARIO" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_BIZ_SCENARIO_URL
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO_URL" MODIFY ("URL_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO_URL" MODIFY ("BIZ_SCENARIO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_EMAIL_ACTION
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" MODIFY ("TO_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" MODIFY ("FROM_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EMAIL_ACTION" ADD CONSTRAINT "PK_GE_MONITOR_EMAIL_ACTION" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_EUM_URL
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_EUM_URL" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EUM_URL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EUM_URL" ADD CONSTRAINT "PK_GE_MONITOR_EUM_URL" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_EUM_URL_AVA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_EUM_URL_AVA" MODIFY ("INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EUM_URL_AVA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EUM_URL_AVA" ADD CONSTRAINT "PK_GE_MONITOR_EUM_URL_AVA" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_EUM_URL_AVA_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_EUM_URL_AVA_STA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EUM_URL_AVA_STA" ADD CONSTRAINT "PK_GE_MONITOR_EUM_URL_AVA_STA" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_EXCEPTION_INFO
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_EXCEPTION_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_EXCEPTION_INFO" ADD CONSTRAINT "PK_GE_MONITOR_EXCEPTION_INFO" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_GROUP
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_GROUP" ADD UNIQUE ("NAME") ENABLE;
  ALTER TABLE "GE_MONITOR_GROUP" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_GROUP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_GROUP" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table GE_MONITOR_METHOD
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("CREATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD" ADD CONSTRAINT "PK_GE_MONITOR_METHOD" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_METHOD_RESPONSETIME
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_METHOD_RESPONSETIME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD_RESPONSETIME" ADD CONSTRAINT "PK_GE_MONITOR_METHOD_RESPONSET" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_METHOD_TL_TEMP
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_METHOD_TL_TEMP" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_METHOD_TL_TEMP" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_METHOD_TRACE_LOG
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_METHOD_TRACE_LOG" MODIFY ("METHOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD_TRACE_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_METHOD_TRACE_LOG" ADD CONSTRAINT "PK_GE_MONITOR_METHOD_TRACE_LOG" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ORACLE_AVA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_AVA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ORACLE_AVA" ADD CONSTRAINT "PK_GE_MONITOR_ORACLE_AVA" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ORACLE_AVA_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_AVA_STA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ORACLE_AVA_STA" ADD CONSTRAINT "PK_GE_MONITOR_ORACLE_AVA_STA" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ORACLE_EVENT_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_EVENT_STA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ORACLE_EVENT_STA" ADD CONSTRAINT "PK_GE_MONITOR_ORACLE_EVENT_STA" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ORACLE_INFO
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ORACLE_INFO" ADD CONSTRAINT "PK_GE_MONITOR_ORACLE_INFO" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_ORACLE_LASTEVENT
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_LASTEVENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_ORACLE_LASTEVENT" ADD CONSTRAINT "PK_GE_MONITOR_ORACLE_LASTEVENT" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS" ADD CONSTRAINT "PK_GE_MONITOR_OS" PRIMARY KEY ("OS_INFO_ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_AVAILABLE
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_AVAILABLE" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_AVAILABLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_AVAILABLE" ADD CONSTRAINT "PK_GE_MONITOR_OS_AVAILABILE" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_AVAILABLETEMP
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_AVAILABLETEMP" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_AVAILABLETEMP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_AVAILABLETEMP" ADD CONSTRAINT "PK_GE_MONITOR_OS_AVAILABLETEMP" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_CPU
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_CPU" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_CPU" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_CPU" ADD CONSTRAINT "PK_GE_MONITOR_OS_CPU" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_DISK
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_DISK" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_DISK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_DISK" ADD CONSTRAINT "PK_GE_MONITOR_OS_DISK" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_RAM
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_RAM" MODIFY ("OS_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_RAM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_RAM" ADD CONSTRAINT "PK_GE_MONITOR_OS_RAM" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_RESPONDTIME
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_RESPONDTIME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_RESPONDTIME" ADD CONSTRAINT "PK_GE_MONITOR_OS_RESPONDTIME" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_SHELL
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_SHELL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_SHELL" ADD CONSTRAINT "PK_GE_MONITOR_OS_SHELL" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_OS_STATI
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_STATI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_OS_STATI" ADD CONSTRAINT "PK_GE_MONITOR_OS_STATI" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_REQUEST_PER_MINUTE
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_REQUEST_PER_MINUTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_REQUEST_PER_MINUTE" ADD CONSTRAINT "PK_GE_MONITOR_REQUEST_PER_MINU" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_RESOURCES
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_RESOURCES" MODIFY ("RESOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_RESOURCES" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_RESOURCES" ADD CONSTRAINT "PK_GE_MONITOR_RESOURCES" PRIMARY KEY ("RESOURCE_ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_SMS
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_SMS" ADD UNIQUE ("PHONENO") ENABLE;
  ALTER TABLE "GE_MONITOR_SMS" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_SMS" MODIFY ("PHONENO" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_SMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_THRESHOLD
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_THRESHOLD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_THRESHOLD" ADD CONSTRAINT "PK_GE_MONITOR_THRESHOLD" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" MODIFY ("CREATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL" ADD CONSTRAINT "PK_GE_MONITOR_URL" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL_METHOD
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_METHOD" MODIFY ("METHOD_ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL_METHOD" MODIFY ("URL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL_RESPONSE_TIME
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_RESPONSE_TIME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL_RESPONSE_TIME" ADD CONSTRAINT "PK_GE_MONITOR_URL_RESPONSE_TIM" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL_TRACE_LOG
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_TRACE_LOG" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL_TRACE_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL_TRACE_LOG" ADD CONSTRAINT "PK_GE_MONITOR_URL_TRACE_LOG" PRIMARY KEY ("ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL_TRACE_LOG_TEMP
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_TRACE_LOG_TEMP" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_URL_TRACE_LOG_TEMP" MODIFY ("URL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GE_MONITOR_URL_VISITS_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_VISITS_STA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "GE_MONITOR_URL_VISITS_STA" ADD CONSTRAINT "PK_GE_MONITOR_URL_VISITS_STA" PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_ACCOUNT_AUTH
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ACCOUNT_AUTH" ADD CONSTRAINT "FK_GE_MONIT_ACCOUNT_GE_MONIT" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "GE_MONITOR_ACCOUNT" ("ID") ON DELETE CASCADE ENABLE;





--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_BIZ_SCENARIO
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO" ADD CONSTRAINT "FK_BUSINESS_SCENARIO" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "GE_MONITOR_APPLICATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_BIZ_SCENARIO_URL
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO_URL" ADD CONSTRAINT "FK_BIZ_SCENARIO_URL_BIZ" FOREIGN KEY ("BIZ_SCENARIO_ID")
	  REFERENCES "GE_MONITOR_BIZ_SCENARIO" ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_BIZ_SCENARIO_URL" ADD CONSTRAINT "FK_BIZ_SCENARIO_URL_URL" FOREIGN KEY ("URL_ID")
	  REFERENCES "GE_MONITOR_URL" ("ID") ENABLE;






--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_GROUP_PERMISSION
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_GROUP_PERMISSION" ADD CONSTRAINT "FKAE243466DE3FB950" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "GE_MONITOR_GROUP" ("ID") ON DELETE CASCADE ENABLE;




--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_ORACLE_AVA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_AVA" ADD CONSTRAINT "FK_GE_MONIT_AVA_DATAB_GE_MONIT" FOREIGN KEY ("DATABASE_ID")
	  REFERENCES "GE_MONITOR_ORACLE_INFO" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_ORACLE_AVA_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_AVA_STA" ADD CONSTRAINT "FK_GE_MONIT_AVA_STA_D_GE_MONIT" FOREIGN KEY ("DATABASE_ID")
	  REFERENCES "GE_MONITOR_ORACLE_INFO" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_ORACLE_EVENT_STA
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_EVENT_STA" ADD CONSTRAINT "FK_GE_MONIT_STA_DATAB_GE_MONIT" FOREIGN KEY ("DATABASE_ID")
	  REFERENCES "GE_MONITOR_ORACLE_INFO" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_ORACLE_LASTEVENT
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_ORACLE_LASTEVENT" ADD CONSTRAINT "FK_GE_MONIT_LASTEVENT_GE_MONIT" FOREIGN KEY ("DATABASE_ID")
	  REFERENCES "GE_MONITOR_ORACLE_INFO" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_AVAILABLE
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_AVAILABLE" ADD CONSTRAINT "FK_GE_MONIT_AVALIABLE_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_AVAILABLETEMP
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_AVAILABLETEMP" ADD CONSTRAINT "FK_GE_MONIT_REFERENCE_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_CPU
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_CPU" ADD CONSTRAINT "FK_GE_MONIT_CPU_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_DISK
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_DISK" ADD CONSTRAINT "FK_GE_MONIT_DISK_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_RAM
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_RAM" ADD CONSTRAINT "FK_GE_MONIT_RAM_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_OS_RESPONDTIME
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_OS_RESPONDTIME" ADD CONSTRAINT "FK_GE_MONIT_RESPOTIME_GE_MONIT" FOREIGN KEY ("OS_INFO_ID")
	  REFERENCES "GE_MONITOR_OS" ("OS_INFO_ID") ON DELETE CASCADE ENABLE;







--------------------------------------------------------
--  Ref Constraints for Table GE_MONITOR_URL_METHOD
--------------------------------------------------------

  ALTER TABLE "GE_MONITOR_URL_METHOD" ADD CONSTRAINT "FK_URL_METHOD_METHOD" FOREIGN KEY ("METHOD_ID")
	  REFERENCES "GE_MONITOR_METHOD" ("ID") ENABLE;
  ALTER TABLE "GE_MONITOR_URL_METHOD" ADD CONSTRAINT "FK_URL_METHOD_URL" FOREIGN KEY ("URL_ID")
	  REFERENCES "GE_MONITOR_URL" ("ID") ENABLE;




